include <string.h> in modules/config_gnome3.cpp
Needed to fix build on Solaris 11:

libproxy/modules/config_gnome3.cpp:190:3: error: ‘memset’ was not declared
 in this scope
   FD_ZERO(&rfds);
   ^

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>