meson: Don't build OSX plugin on iOS
Fails to build with:

../src/backend/plugins/config-osx/config-osx.c:284:29: error: 'SCDynamicStoreCopyProxies' is unavailable: not available on iOS

Which is true, it's only available on macOS 10.1+

https://developer.apple.com/documentation/systemconfiguration/1517088-scdynamicstorecopyproxies